$(document).ready(function() {
    var isOneClick = Boolean('<?php echo $data['oneclick'] ?>');
    var isMasterPass = Boolean('<?php echo $data['mp'] ?>');
    var isBlik = Boolean('<?php echo $data['blik'] ?>');
    var isWidget = Boolean('<?php echo $data['widget'] ?>');
    
    var oneClickRegisterDisableFirstSubmit = true;
    
    var urlSignature = '<?php echo $data['signature_url']; ?>';
    var urlOneClickRegister = '<?php echo $data['oneclick_register_url']; ?>';

    strategyDefault();

    $('body').on('click', 'input[name="strategy"]', function(){
        var target;
    
        $('form[form-target]').hide();
        $('form[form-target] input[type="submit"]').attr('disabled', true);
        
        target = $(this).attr('form-target');
        
        if(getOneClickCardStr() === getOneClickCardSubstr(target)) {
            strategyOneClickCard(target);
        } else if('oneclick_register' === target) {
            strategyOneClickRegister(target);
        } else if('mp' === target) {
            strategyMasterPass(target);
        } else if('blik' === target) {
            strategyBlik(target);
        } else if('dotpay' === target) {
            if(isWidget){
                strategyWidget(target);
            } else {
                strategyNotWidget(target);
            }
        }
    });
    
    $('body').on('input', 'input[name="blik_code"]', function(){
        var target = $(this).attr('form-target');
        var data = {
            type: target,
            channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
            blik: $(this).val()
        };
        
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', true);

        getCHK(data);
    });

    $('body').on('click', '.channel-container', function(){
        var target = 'dotpay';
        var data = {
            type: target,
            widget: isWidget
        };
        
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', true);

        $('input[name="channel"]', this).each(function(key, val){
            var channel = $(val).is(':checked');
            var online = !$(val).parent().parent().hasClass('not-online');

            if(channel && online) {
                data.channel = $(val).val();
                return false;
            }
        });

        getCHK(data);
    });

    $('body').on('click', 'form[form-target] input[type="submit"]', function(){
        var ok = true;
        var checkValid = true;
        
        var target = $(this).attr('form-target');
        
        $('form[form-target="' + target + '"] input[required]').each(function(key, val){
            if(!val.validity.valid) {
                checkValid = false;
                return false;
            }
        });
        
        if('oneclick_register' === target && checkValid && oneClickRegisterDisableFirstSubmit) {
            ok = false;
            runBlockUI();
            oneClickRegister(target);
        }
        
        if(ok && checkValid && 'oneclick_register' !== target) {
            runBlockUI();
        }
        
        return ok;
    });
    
    function strategyOneClickCard(target) {
        var data = {
            type: getOneClickCardStr(),
            channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
            cardhash: $('form[form-target="' + target + '"] input[name="credit_card_customer_id"]').val()
        };
        
        $('form[form-target="' + target + '"]').show();

        if(data.channel && data.cardhash) {
            $.post(urlSignature, data, function(result) {
                $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            });
        }
    }
    
    function oneClickRegister(target) {
        var dataReg = {
            cardtitle: $('form[form-target="' + target + '"] input[id="card_title"]').val()
        }
    
        $.post(urlOneClickRegister, dataReg, function(result) {
            var data = {
                type: target,
                channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
                cardhash: result
            };
            
            $('form[form-target="' + target + '"] input[name="credit_card_customer_id"]').val(result);

            if(data.channel && data.cardhash) {
                $.post(urlSignature, data, function(result) {
                    $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                    oneClickRegisterDisableFirstSubmit = false;
                    $('form[form-target="' + target + '"] input[type="submit"]').click();
                });
            }
        });
    }
    
    function strategyDefault() {
        $('form[form-target]').hide();
        $('form[form-target] input[type="submit"]').attr('disabled', true);
        
        if(!isOneClick && !isMasterPass && !isBlik && !isWidget) {
            $('form[form-target="dotpay"]').show();
            $('form[form-target="dotpay"] input[type="submit"]').attr('disabled', false);
        }
    }
    
    function strategyOneClickRegister(target) {
        $('form[form-target="' + target + '"]').show();
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
    }
    
    function strategyMasterPass(target) {
        var data = {
            type: target,
            channel: $('form[form-target="' + target + '"] input[name="channel"]').val()
        }
        
        $('form[form-target="' + target + '"]').show();

        getCHK(data);
    }
    
    function strategyBlik(target) {
        var data = {
            type: target,
            channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
            blik: $('form[form-target="' + target + '"] input[name="blik_code"]').val()
        };
        
        $('form[form-target="' + target + '"]').show();

        getCHK(data);
    }
    
    function strategyWidget(target) {
        var data = {
            type: target,
            widget: isWidget
        };
        
        $('form[form-target="' + target + '"]').show();
        
        $('form[form-target="' + target + '"] input[name="channel"]').each(function(key, val){
            var channel = $(val).is(':checked');
            var online = !$(val).parent().parent().hasClass('not-online');
            if(channel && online) {
                data.channel = $(val).val();
                return false;
            }
        });

        getCHK(data);
    }
    
    function strategyNotWidget(target) {
        $('form[form-target="' + target + '"]').show();
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
    }
    
    function getCHK(data) {
        if(data.channel) {
            $.post(urlSignature, data, function(result) {
                $('form[form-target="' + data.type + '"] input[name="chk"]').val(result);
                $('form[form-target="' + data.type + '"] input[type="submit"]').attr('disabled', false);
            });
        }
    }
    
    function getOneClickCardStr() {
        return 'oneclick_card';
    }
    
    function getOneClickCardSubstr(target) {
        return target.substr(0, getOneClickCardStr().length);
    }

    function runBlockUI() {
        $.blockUI({
            message: "<?php echo $data['message'] ?>",
            baseZ: 99999,
            overlayCSS: {
                background: "#fff",
                opacity: 0.6
            },
            css: {
                padding: "20px",
                zindex: "9999999",
                textAlign: "center",
                color: "#555",
                border: "3px solid #aaa",
                backgroundColor: "#fff",
                cursor: "wait",
                lineHeight: "24px"
            }
        });
    }
});
