$(document).ready(function() {
    var isOneClick = Boolean('<?php echo $data['oneclick'] ?>');
    var isMasterPass = Boolean('<?php echo $data['mp'] ?>');
    var isBlik = Boolean('<?php echo $data['blik'] ?>');
    var isWidget = Boolean('<?php echo $data['widget'] ?>');
    
    var oneClickRegisterDisableFirstSubmit = true;

    $('form[form-target]').hide();
    
    if(!isOneClick && !isMasterPass && !isBlik && !isWidget) {
        $('label[form-target]').hide();
        $('form[form-target="dotpay"]').show();
        $('form[form-target="dotpay"] input[type="submit"]').attr('disabled', false);
    }

    $('body').on('click', 'input[name="strategy"]', function(){
        $('form[form-target]').hide();
        $('form[form-target="' + $(this).attr('form-target') +'"] input[type="submit"]').attr('disabled', true);

        $(this).each(function(key, val){
            var checked = $(val).is(':checked');
            var target = $(val).attr('form-target');
            
            var oneClickCardSubstr = getOneClickCardStr();
            var targetSubstr = getOneClickCardSubstr(target);

            var data = {};

            if(oneClickCardSubstr === targetSubstr) {
                data.type = oneClickCardSubstr;
                data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();
                data.cardhash = $('form[form-target="' + target + '"] input[name="credit_card_customer_id"]').val();

                if(data.channel && data.cardhash) {
                    $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                        $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                        submitHideShow(target);
                    });
                }
            } else if('oneclick_register' === target) {
                submitHideShow(target);
            } else if('mp' === target) {
                data.type = target;
                data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();

                if(data.channel) {
                    $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                        $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                        submitHideShow(target);
                    });
                }
            } else if('blik' === target) {
                data.type = target;
                data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();
                data.blik = $('form[form-target="' + target + '"] input[name="blik_code"]').val();

                if(data.channel && data.blik) {
                    $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                        $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                        submitHideShow(target);
                    });
                }
            } else if('dotpay' === target) {
                if(isWidget){
                    data.type = target;
                    data.widget = isWidget;

                    $('form[form-target="' + target + '"] input[name="channel"]').each(function(key, val){
                        var channel = $(val).is(':checked');
                        var online = !$(val).parent().parent().hasClass('not-online');
                        if(channel && online) {
                            data.channel = $(val).val();
                            return false;
                        }
                    });

                    if(data.channel) {
                        $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                            submitHideShow(target);
                        });
                    }
                } else {
                    submitHideShow(target);
                }
            }

            if(checked) {
               $('form[form-target="' + target + '"]').show();
            }
        });
    });
    
    $('body').on('change', 'input[name="bylaw"]', function() {
        $('form[form-target="' + $(this).attr('form-target') + '"] input[type="submit"]').attr('disabled', true);
        submitHideShow($(this).attr('form-target'));
    });
    
    $('body').on('change', 'input[name="personal_data"]', function() {
        $('form[form-target="' + $(this).attr('form-target') + '"] input[type="submit"]').attr('disabled', true);
        submitHideShow($(this).attr('form-target'));
    });
    
    $('body').on('input', 'input[id="card_title"]', function(){
        var target = $(this).attr('form-target');
        
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', true);
        
        submitHideShow(target);
    });

    $('body').on('input', 'input[name="blik_code"]', function(){
        var target = $(this).attr('form-target');
        
        $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', true);

        var data = {
            type: target,
            channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
            blik: $(this).val()
        };

        if(this.validity.valid && data.channel && data.blik) {
            $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                submitHideShow(target);
            });
        }
    });

    $('body').on('click', '.channel-container', function(){
        $('form[form-target] input[type="submit"]').attr('disabled', true);

        var target = 'dotpay';
        var data = {};
        data.type = target;
        data.widget = isWidget;

        $('input[name="channel"]', this).each(function(key, val){
            var channel = $(val).is(':checked');
            var online = !$(val).parent().parent().hasClass('not-online');

            if(channel && online) {
                data.channel = $(val).val();
                return false;
            }
        });

        if(data.channel) {
            $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                submitHideShow(target);
            });
        }
    });

    $('body').on('click', 'form[form-target] input[type="submit"]', function(){
        $('form[form-target="' + $(this).attr('form-target') + '"]').submit();
        return false;
    });
    
    $('body').on('submit', 'form[form-target]', function(){
        var ok = true;
        
        var target = $(this).attr('form-target');
        
        $('input[type="text"]', this).each(function(key, val){
            if(!val.validity.valid) {
                ok = false;
                return false;
            }
        });
        
        if('oneclick_register' === target && oneClickRegisterDisableFirstSubmit) {
            ok = false;
            runBlockUI();
            oneClickRegister(target);
        }
        
        if(ok && 'oneclick_register' !== target) {
            runBlockUI();
        }
        
        return ok;
    });
    
    function oneClickRegister(target) {
        var dataReg = {
            cardtitle: $('form[form-target="' + target + '"] input[id="card_title"]').val()
        }
    
        $.post('<?php echo $data['oneclick_register_url']; ?>', dataReg, function(result) {
            var data;
            
            $('form[form-target="' + target + '"] input[name="credit_card_customer_id"]').val(result);

            data = {
                type: target,
                channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
                cardhash: result
            };

            if(data.channel && data.cardhash) {
                $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                    $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                    oneClickRegisterDisableFirstSubmit = false;
                    $('form[form-target="' + target + '"]').submit();
                });
            }
        });
    }

    function submitHideShow(target) {
        var result = false;

        var checkBylaw = false;
        var checkPersonalData = false;
        var checkBlikCode = false;
        var checkCardTitle = false;

        if(target) {
            checkBylaw = $('form[form-target="' + target + '"] input[name="bylaw"]').is(':checked');
            checkPersonalData = $('form[form-target="' + target + '"] input[name="personal_data"]').is(':checked')
            $('form[form-target="' + target + '"] input[name="blik_code"]').each(function(key, val){
                if(val.validity.valid) {
                    checkBlikCode = true;
                    return false;
                }
            });
            $('form[form-target="' + target + '"] input[id="card_title"]').each(function(key, val){
                if(val.validity.valid) {
                    checkCardTitle = true;
                    return false;
                }
            });
        }
        
        var oneClickCardSubstr = getOneClickCardStr();
        var targetSubstr = getOneClickCardSubstr(target);

        if(oneClickCardSubstr === targetSubstr && checkBylaw && checkPersonalData) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        } else if('oneclick_register' === target && checkCardTitle) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        } else if('mp' === target && checkBylaw && checkPersonalData) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        } else if('blik' === target && checkBlikCode && checkBylaw && checkPersonalData) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        } else if('dotpay' === target && checkBylaw && checkPersonalData) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        } else if('dotpay' === target && (isOneClick || isMasterPass || isBlik) && !isWidget) {
            $('form[form-target="' + target + '"] input[type="submit"]').attr('disabled', false);
            result = true;
        }

        return result;
    }
    
    function getOneClickCardStr() {
        return 'oneclick_card';
    }
    
    function getOneClickCardSubstr(target) {
        return target.substr(0, getOneClickCardStr().length);
    }

    function runBlockUI() {
        $.blockUI({
            message: "<?php echo $data['message'] ?>",
            baseZ: 99999,
            overlayCSS: {
                background: "#fff",
                opacity: 0.6
            },
            css: {
                padding: "20px",
                zindex: "9999999",
                textAlign: "center",
                color: "#555",
                border: "3px solid #aaa",
                backgroundColor: "#fff",
                cursor: "wait",
                lineHeight: "24px"
            }
        });
    }
});
